project_id = "mecywtbdycgfhsigztaf"

[functions.chat]
verify_jwt = false

[functions.realtime-voice]
verify_jwt = false

[functions.habits-analysis]
verify_jwt = false

[functions.ai-insights]
verify_jwt = false

[functions.daily-tip]
verify_jwt = false